#include <stdint.h>

static char *unknown = "Unknown";

static char *parameter_codes[] = {
    "Reserved",
    "Authentication",
    "Capabilities",
    //Unassigned from 3 - 254
    "Unassigned",
    //Extended length is 255
    "Extended Length"
};

char *parameter_string(uint8_t parameter_code) {
    if (parameter_code > 2) {
        return parameter_codes[3];
    }

    if (parameter_code == 255) {
        return parameter_codes[4];
    }

    return parameter_codes[ parameter_code ];
}


static char *capability_codes[] = {
    "Reserved",
    "Multiprotocol Extensions for BGP-4",
    "Route Refresh Capability for BGP-4",
    "Outbound Route Filtering Capability",
    "Multiple routes to a destination capability",
    "Extended Next Hop Encoding",
    "BGP Extended Message",
    "BGPsec Capability",
    "Multiple Labels Capability",
    "BGP Role",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Graceful Restart Capability",
    "Support for 4-octet AS number capability",
    "Deprecated (2003-03-06)",
    "Support for Dynamic Capability (capability specific)",
    "Multisession BGP Capability",
    "ADD-PATH Capability",
    "Enhanced Route Refresh Capability",
    "Long-Lived Graceful Restart (LLGR) Capability",
    "Routing Policy Distribution",
    "FQDN Capability",
    "BFD Capability",
    "Software Version Capability",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Prestandard Route Refresh",
    "Prestandard Outbound Route Filtering,          prestandard Routing Policy Distribution",
    "Prestandard Outbound Route Filtering",
    "Prestandard Multisession",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Prestandard FQDN",
    "Prestandard OPERATIONAL message",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved for Experimental Use",
    "Reserved"
};

char *capability_string(uint8_t capability_code) {
    return capability_codes[ capability_code ];
}

static char *afi_strings[] = {
    "Reserved",
    "IP (IP version 4)",
    "IP6 (IP version 6)",
    "NSAP",
    "HDLC (8-bit multidrop)",
    "BBN 1822",
    "802 ",
    "E.163",
    "E.164 (SMDS, Frame Relay, ATM)",
    "F.69 (Telex)",
    "X.121 (X.25, Frame Relay)",
    "IPX",
    "Appletalk",
    "Decnet IV",
    "Banyan Vines",
    "E.164 with NSAP format subaddress",
    "DNS (Domain Name System)",
    "Distinguished Name",
    "AS Number",
    "XTP over IP version 4",
    "XTP over IP version 6",
    "XTP native mode XTP",
    "Fibre Channel World-Wide Port Name",
    "Fibre Channel World-Wide Node Name",
    "GWID",
    "AFI for L2VPN information",
    "MPLS-TP Section Endpoint Identifier",
    "MPLS-TP LSP Endpoint Identifier",
    "MPLS-TP Pseudowire Endpoint Identifier",
    "MT IP: Multi-Topology IP version 4",
    "MT IPv6: Multi-Topology IP version 6",
    "BGP SFC"
};

char *afi_string(uint16_t afi) {
    if (afi > 31) {
        return unknown;
    }

    return afi_strings[ afi ];
}


static char *safi_strings[] = {
    "Reserved",
    "Unicast",
    "Multicast",
    "Reserved",
    "Network Layer Reachability Information (NLRI)    with MPLS Labels",
    "MCAST-VPN",
    "Network Layer Reachability Information used      for Dynamic Placement of Multi-Segment Pseudowires",
    "Encapsulation SAFI (OBSOLETE)",
    "MCAST-VPLS",
    "BGP SFC",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Tunnel SAFI",
    "Virtual Private LAN Service (VPLS)",
    "BGP MDT SAFI",
    "BGP 4over6 SAFI",
    "BGP 6over4 SAFI",
    "Layer-1 VPN auto-discovery information",
    "BGP EVPNs",
    "BGP-LS",
    "BGP-LS-VPN",
    "SR TE Policy SAFI",
    "SD-WAN Capabilities",
    "Routing Policy SAFI",
    "Classful-Transport SAFI",
    "Tunneled Traffic Flowspec",
    "MCAST-TREE",
    "BGP-DPS (Dynamic Path Selection)",
    "BGP-LS-SPF",
    "Unassigned",
    "Unassigned",
    "BGP CAR",
    "BGP VPN CAR",
    "BGP-MUP SAFI",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "MPLS-labeled VPN address",
    "Multicast for BGP/MPLS IP Virtual Private Networks",
    "Reserved",
    "Reserved",
    "Route Target constrains",
    "Dissemination of Flow Specification rules",
    "L3VPN Dissemination of Flow Specification rules",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "VPN auto-discovery",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved for Private Use",
    "Reserved"
};

char *safi_string(uint16_t safi) {
    return safi_strings[ safi ];
}

char *path_attribute_names[] = {
    "Reserved",
    "ORIGIN",
    "AS_PATH",
    "NEXT_HOP",
    "MULTI_EXIT_DISC",
    "LOCAL_PREF",
    "ATOMIC_AGGREGATE",
    "AGGREGATOR",
    "COMMUNITIES",
    "ORIGINATOR_ID",
    "CLUSTER_LIST",
    "DPA",
    "ADVERTISER",
    "RCID_PATH / CLUSTER_ID",
    "MP_REACH_NLRI",
    "MP_UNREACH_NLRI",
    "EXTENDED COMMUNITIES",
    "AS4_PATH",
    "AS4_AGGREGATOR",
    "SAFI Specific Attribute (SSA)",
    "Connector Attribute",
    "AS_PATHLIMIT",
    "PMSI_TUNNEL",
    "Tunnel Encapsulation",
    "Traffic Engineering",
    "IPv6 Address Specific Extended Community",
    "AIGP",
    "PE Distinguisher Labels",
    "BGP Entropy Label Capability Attribute",
    "BGP-LS Attribute",
    "Deprecated",
    "Deprecated",
    "LARGE_COMMUNITY",
    "BGPsec_Path",
    "BGP Community Container Attribute",
    "Only to Customer (OTC)",
    "BGP Domain Path (D-PATH)",
    "SFP attribute",
    "BFD Discriminator",
    "BGP Next Hop Dependent Capabilities",
    "BGP Prefix-SID",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "ATTR_SET",
    "Deprecated",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Deprecated",
    "Deprecated",
    "Deprecated",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Reserved for development"
};

char *path_attribute_string(uint8_t type) {
    return path_attribute_names[type];
}


char *path_attribute_flags[][4] = {
    { "well-known", "optional" },
    { "non-transitive", "transitive" },
    { "complete", "partial" },
    { "standard", "extended" }
};


enum {
    PA_FLAG_OPTIONAL,
    PA_FLAG_TRANSITIVE,
    PA_FLAG_PARTIAL,
    PA_FLAG_EXTENDED
};

char *pa_flag_optional_string(uint8_t flag) {
    return path_attribute_flags[PA_FLAG_OPTIONAL][ (flag & 0x80) >> 7 ];
}

char *pa_flag_transitive_string(uint8_t flag) {
    return path_attribute_flags[PA_FLAG_TRANSITIVE][ (flag & 0x80) >> 7 ];
}

char *pa_flag_partial_string(uint8_t flag) {
    return path_attribute_flags[PA_FLAG_PARTIAL][ (flag & 0x80) >> 7 ];
}

char *pa_flag_extended_string(uint8_t flag) {
    return path_attribute_flags[PA_FLAG_EXTENDED][ (flag & 0x80) >> 7 ];
}
